baseURL = 'https://hyperagon.github.io/'
languageCode = 'en-us'
title = 'Hyperagon'
theme = 'PaperMod'

[params]
env = "production"
title = "Magic"
description = "Programmer ğŸ§‘â€ğŸ’»ï¸ by Day, Wizard ğŸ§™â€â™€ï¸ï¸ by Night"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Hyperagon"
favicon = './static/favicon.ico'

  [assets]
    favicon = "static/hyperagon.ico"
    apple_touch_icon = "static/hyperagon.png"

  [params.contact]
    email = 'viminoâ€¢net@gmailâ€¢com'

